INFO:root:Predictions: [498.95961036], Actual: index
23912     631.0
3270      405.0
15565     689.0
4283      722.0
8734      504.0
          ...  
5059     1179.0
21081     287.0
16316    1066.0
26043     380.0
3185      324.0
Name: price, Length: 5177, dtype: float64
INFO:root:Predictions: [498.95961036], Actual: index
23912     631.0
3270      405.0
15565     689.0
4283      722.0
8734      504.0
          ...  
5059     1179.0
21081     287.0
16316    1066.0
26043     380.0
3185      324.0
Name: price, Length: 5177, dtype: float64
INFO:root:Predictions: [498.95961036], Actual: index
23912     631.0
3270      405.0
15565     689.0
4283      722.0
8734      504.0
          ...  
5059     1179.0
21081     287.0
16316    1066.0
26043     380.0
3185      324.0
Name: price, Length: 5177, dtype: float64
ERROR:asyncio:Task was destroyed but it is pending!
task: <Task pending name='Task-3' coro=<Kernel.poll_control_queue() running at /opt/anaconda3/envs/ml/lib/python3.10/site-packages/ipykernel/kernelbase.py:309> wait_for=<Future pending cb=[Task.task_wakeup()]> cb=[_chain_future.<locals>._call_set_state() at /opt/anaconda3/envs/ml/lib/python3.10/asyncio/futures.py:392]>
INFO:root:Predictions: [498.95961036], Actual: index
23912     631.0
3270      405.0
15565     689.0
4283      722.0
8734      504.0
          ...  
5059     1179.0
21081     287.0
16316    1066.0
26043     380.0
3185      324.0
Name: price, Length: 5177, dtype: float64
INFO:root:Predictions: [498.95961036], Actual: index
23912     631.0
3270      405.0
15565     689.0
4283      722.0
8734      504.0
          ...  
5059     1179.0
21081     287.0
16316    1066.0
26043     380.0
3185      324.0
Name: price, Length: 5177, dtype: float64
